version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    volumes:
      - ./shared-db:/db
    networks:
      - backend

  task-service:
    build: ./task-service
    ports:
      - "3002:3002"
    volumes:
      - ./shared-db:/db
    networks:
      - backend

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./nginx-html:/app/frontend/public:ro     # ✅ esta es la clave
    networks:
      - backend
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./nginx-html:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - backend


networks:
  backend:
    driver: bridge
